title: Project
columns:
  -
    width: 3/4
    sections:
      content:
        type: fields
        fields:
          thumbnail:
            label: Thumbnail
            type: files
            multiple: false
            layout: cards
            size: small
            required: true
          new:
            label: New
            type: toggle
          tags:
            label: Tags
            type: tags
            accept: options
            options: query
            query:
              fetch: site.find('work').tags.toStructure
              text: "{{ structureItem.name }}"
              value: "{{ structureItem.name }}"
  -
    width: 1/4
    sections:
      files:
        type: files