title: Work
pages: true
columns:
  -
    width: 1/4
    sections:
      tags:
        type: fields
        fields:
          tags:
            type: structure
            columns:
              name:
                width: 1
            fields:
              name:
                type: text
                required: true
              color:
                type: color
                required: true
  -
    width: 3/4
    sections:
      pages:
        type: pages
        limit: 150
        templates:
          - project
          - about
        create:
          - project